name: "web_app"
mode: "dev"
port: ":8081"
version: "v0.0.1"
log:
  level: "debug"
  filename: "web_app.log"
  #  最大容量 MB
  max_size: 200
  #  备份天数
  max_age: 30
  #  备份数量
  max_backups: 7
mysql:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "currency_exchange_db"
  MaxIdleConn: 10
  MaxOpenConn: 50
redis:
  host: "59.153.167.78"
  port: "6379"
  password: "123456"
  db: 0
  pool_size: 100